import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          The two borders have the same styles applied, but are different
          colors. In <code className={styles.code}>tailwind.config.js</code> the
          default border color is set to blue. Removing the default color also
          results in two different border colors despite the same classes being
          applied to the elements.
        </p>

        <div className={styles.grid}>
          <article className={styles.card}>
            Styled with CSS Modules + Tailwind
          </article>
          <article className="h-36 w-36 border rounded p-4 m-4">
            Styled with inline Tailwind
          </article>
        </div>
      </main>
    </div>
  );
};

export default Home;
